### ISSUE TITLE
Create option for inertia...

### ISSUE THREAD

**Issue by alan412** [Beta8397/virtual_robot#15]
We were noticing that one major difference between testing with the simulator and on our robot is that the simulator has no inertia.    

It would be interesting to be able to add some inertia in (just like the option for motor error) where the wheels had a limit of how fast they could change.

**Comment by jkenney2** [comment]
Yes,

It is essentially a "math-based" rather than a "physics-based" simulator. Changes in motor speed occur instantaneously, and there is no skidding of the wheels. Motor behavior is the same regardless of whether in RUN_USING_ENCODER or RUN_WITHOUT_ENCODER mode.

It would be pretty easy to modify the DcMotorImpl class to simulate some inertia, and add a slider in the UI to control it. I'll look at that. 

I'm not sure how much it would improve the difference between simulator and real robot, as it wouldn't account for differing loads on the different wheels, and the effect of skidding. But, it would be interesting to try.

**Comment by jkenney2** [comment]
Just created a new branch, "inertia", and implemented the suggested change in it. I think it works as expected; give it a try. Not yet merged into the master branch.

**Comment by jkenney2** [comment]
Merged "inertia" branch into master.
