### ISSUE TITLE
Virtual Controller not displaying

### ISSUE THREAD

**Issue by mbcaftc** [Beta8397/virtual_robot#2]
Running Mac OSX 10.13.6 with Java SDK 1.8.0_201.  I can run the program and run the OpModes and we've been able to test Autonomous modes (which is awesome!!), but the controller never displays.  Do get the following in debug:
`Exception in thread "Thread-7" java.lang.NullPointerException
	at teamcode.LineFollow.runOpMode(LineFollow.java:16)
	at virtual_robot.controller.VirtualRobotController.runOpModeAndCleanUp(VirtualRobotController.java:180)
	at virtual_robot.controller.VirtualRobotController.access$400(VirtualRobotController.java:33)
	at virtual_robot.controller.VirtualRobotController$2.run(VirtualRobotController.java:133)
	at java.lang.Thread.run(Thread.java:748)`

**Comment by jkenney2** [comment]
Virtual Robot now allows use of a "real" gamepad. Just plug it in to the computer before running. The "virtual" gamepad was removed. If you'd rather use the "virtual" gamepad, grab the commit from 2/15/2019 titled "Fixed but in ..." (intended title was "Fixed bug in...". This was developed on a windows system and hasn't been tested on a Mac. The "real" gamepad capability is obtained through use of JamePad software (Copyright William Hartman, 2016). It is supposed to be compatible with Mac OS as well as Windows (although apparently with Mac OS you need separate drivers if you're using XBox gamepad). If you continue to have issues, please let us know. Also, I will see if I can reproduce the exception you are getting. Thanks for trying Virtual Robot!

**Comment by jkenney2** [comment]
I have reproduced your Exception. I suspect you tried running the LineFollow op mode using the Mechanum Bot configuration. That op mode is only compatible with the two-wheel bot.  The "left" and "right" motor variables remain null, because the Mechanum Bot configuration does not include motors named "left_motor" or "right_motor". So when the op mode tries to call their methods, the NullPointerException is thrown. In the real FTC SDK, the exception would be thrown up front when the hardwareMap.get() call fails, rather than just leaving the variable null. Also, I realized in doing this that the Line Follow op mode doesn't work now that the field was changed to Rover Ruckus. The original field had a much thicker diagonal line that worked well for line following.

**Comment by johnduval** [comment]
Thanks for the information (this is mbcaftc's coach).  This is awesome!  We plan on implementing this for onboarding new programmers next season, especially for autonomous.  I've done some quick testing and working great. It will be a lot easier to get the basics of robot control using this than waiting for builders to "finish" the robot!

**Comment by jkenney2** [comment]
John,
Thanks for the feedback. We’ll continue to work on this. The most recent additions are support for an X-Drive configuration (four Omni Wheels) and adding left and right trigger functionality for the real gamepad (which we initially overlooked). Thoughts for upgrades in the future include additional motor options (currently it emulates Neverest 40 motors) and an API for a gyro that emulates the IMU in the REV expansion hub (current gyro API is more like the Modern Robotics gyro).
Jim Kenney

**Comment by johnduval** [comment]
Those sound great!  If there's anything I can do to help, let us know.  Though any help would probably be on programming OpModes or creating instructions versus backend APIs and developing functionality.  As the programming mentor, it is far from my speciality and mostly hack it together.
