### ISSUE TITLE
left_motor in config not defined

### ISSUE THREAD

**Issue by nreynolds2003** [Beta8397/virtual_robot#74]
It is literally what the title says. The application says that it is not defined, using try/catch, and as such, I can't access the code needed to change it. java.lang.IllegalArgumentException, No com.qualcomm.robotcore.hardware.CRServo named back_crservo is found. Please help me define it. Thank you!

**Comment by jkenney2** [comment]
@nreynolds2003 

I suspect the issue is that you are trying to run an opmode that is not compatible with the robot configuration you have selected. The only robot configuration that has a motor called "left_motor" is the Two-wheeled bot. So if you try to run an op mode meant for that robot, but have some other robot configuration selected (e.g., Mecanum bot), an exception will be thrown. Unfortunately, as you point out, the system doesn't do very well at pointing you to exactly where in the op mode the exception arose. I should look at making that better.

To find out what hardware objects are available in each robot config, just run the app and select a robot config, but don't run an op mode. The telemetry area will then show you all of the hardware configuration entries for that bot.

Let me know if you continue to have problems with this.

**Comment by nreynolds2003** [comment]
Alright, thank you for being so quick! Thank you for your help!

**Comment by jkenney2** [comment]
@nreynolds2003 
Just added code to print a stack trace when exceptions are thrown by op mode code, with clickable links to take you to the source of exception.

**Comment by nreynolds2003** [comment]
Thank you! This will solve a lot of problems in the future!
